# Generated by Django 6.0.1 on 2026-07-03 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPathItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('content_type', models.CharField(choices=[('lesson', 'Lesson'), ('quiz', 'Quiz'), ('grammar', 'Grammar Topic'), ('vocabulary', 'Vocabulary Practice'), ('diagnostic', 'Diagnostic Test'), ('review', 'Review Session')], max_length=20, verbose_name='Content Type')),
                ('content_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Content ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('reason', models.TextField(blank=True, verbose_name='Why This?')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='Estimated Time (min)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Path Item',
                'verbose_name_plural': 'Learning Path Items',
                'ordering': ['is_completed', 'priority'],
            },
        ),
    ]
