# Generated by Django 6.0.1 on 2026-07-03 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('what_learned', models.TextField(verbose_name='What did you learn today?')),
                ('what_was_difficult', models.TextField(blank=True, verbose_name='What was difficult?')),
                ('topics_to_revisit', models.TextField(blank=True, verbose_name='Topics to revisit')),
                ('self_rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='Self Rating')),
                ('mood', models.CharField(choices=[('great', 'Great 😄'), ('good', 'Good 🙂'), ('neutral', 'Neutral 😐'), ('tired', 'Tired 😴'), ('frustrated', 'Frustrated 😤')], default='neutral', max_length=15, verbose_name='Mood')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
