# Generated by Django 6.0.1 on 2026-07-03 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text', models.TextField(blank=True, verbose_name='Written Answer')),
                ('file', models.FileField(blank=True, null=True, upload_to='homework/files/', verbose_name='File')),
                ('audio', models.FileField(blank=True, null=True, upload_to='homework/audio/', verbose_name='Audio Recording')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed')], default='pending', max_length=20, verbose_name='Status')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Homework Submission',
                'verbose_name_plural': 'Homework Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text_feedback', models.TextField(verbose_name='Text Feedback')),
                ('audio_feedback', models.FileField(blank=True, null=True, upload_to='feedback/audio/', verbose_name='Audio Feedback')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score')),
                ('grammar_score', models.PositiveSmallIntegerField(default=0, verbose_name='Grammar (0-100)')),
                ('vocabulary_score', models.PositiveSmallIntegerField(default=0, verbose_name='Vocabulary (0-100)')),
                ('fluency_score', models.PositiveSmallIntegerField(default=0, verbose_name='Fluency (0-100)')),
                ('content_score', models.PositiveSmallIntegerField(default=0, verbose_name='Content (0-100)')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='feedback.homeworksubmission')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Feedback',
                'verbose_name_plural': 'Teacher Feedbacks',
            },
        ),
    ]
