# Generated by Django 6.0.1 on 2026-07-03 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('event_type', models.CharField(choices=[('lesson', 'Lesson'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('reminder', 'Reminder'), ('holiday', 'Holiday'), ('goal', 'Goal'), ('completed', 'Completed')], default='reminder', max_length=20, verbose_name='Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Color')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['date', 'time'],
            },
        ),
    ]
