# Generated by Django 6.0.1 on 2026-07-02 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='📝', max_length=10)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Word Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('word', models.CharField(max_length=100, verbose_name='Word')),
                ('pronunciation', models.CharField(blank=True, max_length=200, verbose_name='Pronunciation (IPA)')),
                ('audio', models.FileField(blank=True, null=True, upload_to='vocabulary/audio/', verbose_name='Audio')),
                ('translation_uz', models.CharField(max_length=300, verbose_name='Translation (Uzbek)')),
                ('translation_ru', models.CharField(blank=True, max_length=300, verbose_name='Translation (Russian)')),
                ('definition', models.TextField(blank=True, verbose_name='Definition')),
                ('example_sentence', models.TextField(blank=True, verbose_name='Example sentence')),
                ('example_translation', models.TextField(blank=True, verbose_name='Example translation')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vocabulary/images/', verbose_name='Image')),
                ('synonyms', models.TextField(blank=True, verbose_name='Synonyms')),
                ('antonyms', models.TextField(blank=True, verbose_name='Antonyms')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10, verbose_name='Difficulty')),
                ('part_of_speech', models.CharField(blank=True, max_length=50, verbose_name='Part of speech')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabulary', to='courses.lesson')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='vocabulary.wordcategory')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ['order', 'word'],
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('mastered', 'Mastered')], default='new', max_length=20, verbose_name='Status')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorite')),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('incorrect_count', models.PositiveSmallIntegerField(default=0)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to='vocabulary.word')),
            ],
            options={
                'verbose_name': 'User Word',
                'unique_together': {('user', 'word')},
            },
        ),
    ]
