# Generated by Django 6.0.1 on 2026-07-03 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('skill', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('writing', 'Writing'), ('grammar', 'Grammar'), ('vocabulary', 'Vocabulary')], max_length=20, verbose_name='Skill')),
                ('current_score', models.PositiveSmallIntegerField(default=0, verbose_name='Score (0-100)')),
                ('weekly_xp', models.PositiveIntegerField(default=0, verbose_name='Weekly XP')),
                ('monthly_xp', models.PositiveIntegerField(default=0, verbose_name='Monthly XP')),
                ('total_exercises', models.PositiveIntegerField(default=0, verbose_name='Total Exercises')),
                ('streak_days', models.PositiveSmallIntegerField(default=0, verbose_name='Streak')),
                ('last_practiced', models.DateTimeField(blank=True, null=True, verbose_name='Last Practiced')),
                ('last_weekly_reset', models.DateField(blank=True, null=True)),
                ('last_monthly_reset', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Progress',
                'verbose_name_plural': 'Skill Progresses',
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
