# Generated by Django 6.0.1 on 2026-07-03 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('date', models.DateField(verbose_name='Date')),
                ('minutes_studied', models.PositiveIntegerField(default=0, verbose_name='Minutes Studied')),
                ('xp_earned', models.PositiveIntegerField(default=0, verbose_name='XP Earned')),
                ('lessons_completed', models.PositiveSmallIntegerField(default=0, verbose_name='Lessons Completed')),
                ('quizzes_completed', models.PositiveSmallIntegerField(default=0, verbose_name='Quizzes Completed')),
                ('words_reviewed', models.PositiveSmallIntegerField(default=0, verbose_name='Words Reviewed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Session',
                'verbose_name_plural': 'Study Sessions',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
