# Generated by Django 6.0.1 on 2026-07-03 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('test_type', models.CharField(choices=[('placement', 'Placement Test'), ('grammar', 'Grammar Test'), ('vocabulary', 'Vocabulary Test'), ('reading', 'Reading Level'), ('listening', 'Listening Level'), ('writing', 'Writing Level')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='Time Limit (min)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Diagnostic Test',
                'verbose_name_plural': 'Diagnostic Tests',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('percentage', models.PositiveSmallIntegerField(default=0)),
                ('cefr_level', models.CharField(blank=True, max_length=2, verbose_name='CEFR Level')),
                ('recommendation', models.TextField(blank=True, verbose_name='Recommendation')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_attempts', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='diagnostic.diagnostictest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text', models.TextField(verbose_name='Question')),
                ('question_type', models.CharField(choices=[('multiple', 'Multiple Choice'), ('text', 'Text Answer'), ('true_false', 'True / False')], default='multiple', max_length=20, verbose_name='Type')),
                ('option_a', models.CharField(blank=True, max_length=300)),
                ('option_b', models.CharField(blank=True, max_length=300)),
                ('option_c', models.CharField(blank=True, max_length=300)),
                ('option_d', models.CharField(blank=True, max_length=300)),
                ('correct_answer', models.CharField(max_length=300, verbose_name='Correct Answer')),
                ('explanation', models.TextField(blank=True, verbose_name='Explanation')),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2, verbose_name='CEFR Level')),
                ('points', models.PositiveSmallIntegerField(default=1, verbose_name='Points')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='diagnostic.diagnostictest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('given_answer', models.CharField(blank=True, max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.PositiveSmallIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='diagnostic.diagnosticattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.diagnosticquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
