# Generated by Django 6.0.1 on 2026-07-03 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('bio', models.TextField(blank=True, verbose_name='Professional Bio')),
                ('skills_summary', models.TextField(blank=True, verbose_name='Skills Summary')),
                ('goals', models.TextField(blank=True, verbose_name='Learning Goals')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('item_type', models.CharField(choices=[('writing', 'Writing Task'), ('speaking', 'Speaking Record'), ('project', 'Project'), ('homework', 'Homework'), ('achievement', 'Achievement')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(blank=True, null=True, upload_to='portfolio/', verbose_name='File')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score')),
                ('teacher_feedback', models.TextField(blank=True, verbose_name='Teacher Feedback')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['-date'],
            },
        ),
    ]
