# Generated by Django 6.0.1 on 2026-07-07 15:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rated At'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='rated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rated_portfolio_items', to=settings.AUTH_USER_MODEL, verbose_name='Rated By'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 to 5 stars', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Admin Rating'),
        ),
    ]
