# Generated by Django 6.0.1 on 2026-07-02 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True)),
                ('level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Pre-Intermediate'), ('B2', 'B2 - Intermediate'), ('C1', 'C1 - Upper'), ('C2', 'C2 - Advanced')], default='A1', max_length=5, verbose_name='Level')),
                ('explanation', models.TextField(verbose_name='Explanation')),
                ('examples', models.TextField(blank=True, verbose_name='Examples')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('icon', models.CharField(default='📝', max_length=10, verbose_name='Icon')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grammar Topic',
                'verbose_name_plural': 'Grammar Topics',
                'ordering': ['order', 'level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GrammarExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('exercise_type', models.CharField(choices=[('fill_blank', 'Fill in the blank'), ('multiple_choice', 'Multiple choice'), ('reorder', 'Reorder words'), ('transform', 'Transform sentence')], max_length=20, verbose_name='Type')),
                ('question', models.TextField(verbose_name='Question')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Options')),
                ('correct_answer', models.TextField(verbose_name='Correct answer')),
                ('explanation', models.TextField(blank=True, verbose_name='Explanation')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='grammar.grammartopic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('sentence', models.CharField(max_length=500, verbose_name='English sentence')),
                ('translation', models.CharField(max_length=500, verbose_name='Translation')),
                ('explanation', models.CharField(blank=True, max_length=300, verbose_name='Short explanation')),
                ('is_correct', models.BooleanField(default=True, verbose_name='Correct form')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_examples', to='grammar.grammartopic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserGrammarProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('exercises_completed', models.PositiveSmallIntegerField(default=0)),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammar.grammartopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
